CREATE TABLE [dbo].[Products]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [type_id] INT NOT NULL, 
    [language_id] INT NOT NULL, 
    [category_id] INT NOT NULL, 
    [title] NVARCHAR(50) NOT NULL, 
    [price] MONEY NOT NULL, 
    [selling_price] MONEY NOT NULL, 
    [special_price] MONEY NOT NULL, 
    [short_description] NVARCHAR(MAX) NOT NULL, 
    [author] NVARCHAR(MAX) NOT NULL, 
    [release_date] DATE NOT NULL, 
    [is_rentable] BIT NOT NULL, 
    [is_in_library] BIT NOT NULL,  
    [min_rent_days] INT NULL, 
    [publisher] NVARCHAR(MAX) NOT NULL, 
    [ image_path] NVARCHAR(MAX) NOT NULL,
	[special_price_from_date] DATE NULL, 
    [special_price_to_date] DATE NULL, 
    [days_of_sale] INT NULL,
	[long_description] NVARCHAR(MAX) NULL,
	[rent_amount] MONEY NULL,
)
